on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

# here's what we need to do:
# When a PR is created

jobs:
  create_multi_prs:
    runs-on:
    strategy:
      matrix:
        projects: ["a-35wvtmrwghmps", "b-mtvdchuoitkcw", "c-gpng2oj2s22ey"]
    steps:
      run: echo "I'm evaluating ${{ matrix.projects }}"
